import { GoalPriority } from "../types/goal";

export interface DestinationPreset {
  key: string;
  title: string;
  titleFr: string;
  category: string;
  description: string;
  descriptionFr: string;
  defaultAmount: number;
  defaultMonthsAhead: number;
  priority: GoalPriority;
  iconName: string;
  tag: string;
  tagFr: string;
}

export const DESTINATION_PRESETS: DestinationPreset[] = [
  {
    key: "start-business",
    title: "Start a business",
    titleFr: "Lancer mon entreprise",
    category: "BUSINESS",
    description: "Launch a consultancy, venture, or digital studio capital reserve.",
    descriptionFr: "Capital de départ, équipements, trésorerie et lancement d'activité.",
    defaultAmount: 500000,
    defaultMonthsAhead: 24,
    priority: "HIGH",
    iconName: "Briefcase",
    tag: "Venture",
    tagFr: "Entreprise",
  },
  {
    key: "buy-home",
    title: "Buy a home",
    titleFr: "Acheter une maison",
    category: "PROPERTY",
    description: "Land deposit, construction fund, or home purchase down payment.",
    descriptionFr: "Apport personnel, achat de terrain, construction ou immobilier.",
    defaultAmount: 1500000,
    defaultMonthsAhead: 36,
    priority: "HIGH",
    iconName: "Home",
    tag: "Property",
    tagFr: "Immobilier",
  },
  {
    key: "travel",
    title: "Travel & Dream trip",
    titleFr: "Voyager / Séjour de rêve",
    category: "LIFESTYLE",
    description: "Major international exploration, safari expedition, or sabbatical retreat.",
    descriptionFr: "Vacances à l'étranger, expédition, lune de miel ou sabbatique.",
    defaultAmount: 250000,
    defaultMonthsAhead: 10,
    priority: "LOW",
    iconName: "Plane",
    tag: "Experience",
    tagFr: "Voyage",
  },
  {
    key: "invest",
    title: "Invest & Grow Wealth",
    titleFr: "Investir & Capitaliser",
    category: "INVESTMENT",
    description: "Treasury bonds, equities, real estate syndicates, or commercial paper.",
    descriptionFr: "Titres financiers, obligations, bourse ou fonds d'investissement.",
    defaultAmount: 1000000,
    defaultMonthsAhead: 24,
    priority: "HIGH",
    iconName: "LineChart",
    tag: "Compounding",
    tagFr: "Investissement",
  },
  {
    key: "emergency-fund",
    title: "Emergency fund",
    titleFr: "Fonds d'urgence",
    category: "SECURITY",
    description: "3 to 6 months of living expenses safely preserved in liquid MMF.",
    descriptionFr: "3 à 6 mois de charges fixes de sécurité en épargne disponible.",
    defaultAmount: 350000,
    defaultMonthsAhead: 12,
    priority: "CRITICAL",
    iconName: "Shield",
    tag: "Resilience",
    tagFr: "Sécurité",
  },
  {
    key: "buy-car",
    title: "Buy a vehicle",
    titleFr: "Acheter un véhicule",
    category: "ASSET",
    description: "Vehicle purchase or down payment for personal or business mobility.",
    descriptionFr: "Achat automobile, moto ou premier apport de transport.",
    defaultAmount: 850000,
    defaultMonthsAhead: 18,
    priority: "MEDIUM",
    iconName: "Car",
    tag: "Mobility",
    tagFr: "Mobilité",
  },
  {
    key: "education",
    title: "Education & Skills",
    titleFr: "Formation & Études",
    category: "EDUCATION",
    description: "Postgraduate degree, professional certifications, or specialized bootcamps.",
    descriptionFr: "Diplôme, formation continue, certification ou compétences.",
    defaultAmount: 400000,
    defaultMonthsAhead: 14,
    priority: "HIGH",
    iconName: "GraduationCap",
    tag: "Growth",
    tagFr: "Formation",
  },
  {
    key: "debt-free",
    title: "Become debt-free",
    titleFr: "Rembourser mes dettes",
    category: "DEBT_REDUCTION",
    description: "Accelerated payoff of bank loans, SACCO balances, and credit lines.",
    descriptionFr: "Remboursement accéléré des emprunts et libération financière.",
    defaultAmount: 300000,
    defaultMonthsAhead: 12,
    priority: "CRITICAL",
    iconName: "TrendingDown",
    tag: "Freedom",
    tagFr: "Dettes",
  },
  {
    key: "build-savings",
    title: "Build savings",
    titleFr: "Constituer une réserve",
    category: "SAVINGS",
    description: "Disciplined capital accumulation to build long-term wealth cushion.",
    descriptionFr: "Épargne systématique pour matelas de précaution à long terme.",
    defaultAmount: 600000,
    defaultMonthsAhead: 20,
    priority: "HIGH",
    iconName: "PiggyBank",
    tag: "Accumulation",
    tagFr: "Épargne",
  },
  {
    key: "custom",
    title: "Custom goal",
    titleFr: "Objectif sur-mesure",
    category: "CUSTOM",
    description: "Define your own unique financial aspiration and timeline.",
    descriptionFr: "Définissez votre propre projet de vie et votre horizon temporel.",
    defaultAmount: 500000,
    defaultMonthsAhead: 18,
    priority: "HIGH",
    iconName: "Compass",
    tag: "Personal",
    tagFr: "Personnalisé",
  },
];
