import { InvestmentAsset } from "@/lib/types/investments";

export const INITIAL_DEMO_INVESTMENTS: InvestmentAsset[] = [
  {
    id: "inv-1",
    asset_name: "CIC Money Market Fund (MMF)",
    asset_class: "MMF",
    initial_invested: 350000,
    current_market_value: 395000,
    annual_yield_percent: 11.5,
    monthly_income_generated: 3785,
    institution_name: "CIC Group Asset Management",
    notes: "High liquidity reserve yielding ~11.5% p.a.",
  },
  {
    id: "inv-2",
    asset_name: "Stima Sacco Shares & Deposits",
    asset_class: "SACCO",
    initial_invested: 200000,
    current_market_value: 248000,
    annual_yield_percent: 13.0,
    monthly_income_generated: 2686,
    institution_name: "Stima DT Sacco",
    notes: "Annual dividend yield @ 13% paid out in Q1.",
  },
  {
    id: "inv-3",
    asset_name: "Safaricom PLC (NSE: SCOM)",
    asset_class: "STOCKS",
    initial_invested: 150000,
    current_market_value: 172000,
    annual_yield_percent: 7.2,
    monthly_income_generated: 1032,
    institution_name: "Nairobi Securities Exchange",
    notes: "Long-term telecom equity holding.",
  },
  {
    id: "inv-4",
    asset_name: "3-Yr Fixed Infrastructure Treasury Bond",
    asset_class: "BONDS",
    initial_invested: 500000,
    current_market_value: 565000,
    annual_yield_percent: 14.2,
    monthly_income_generated: 6685,
    institution_name: "Central Bank of Kenya",
    notes: "Tax-free semi-annual coupon payment.",
  },
  {
    id: "inv-5",
    asset_name: "Bitcoin (BTC) Reserve",
    asset_class: "CRYPTO",
    initial_invested: 80000,
    current_market_value: 124000,
    annual_yield_percent: 0.0,
    monthly_income_generated: 0,
    institution_name: "Cold Storage Wallet",
    notes: "Digital store-of-value allocation (~8% of total portfolio).",
  },
];
